import React, { useState } from "react";
import "./Login.css";
import { Link, useHistory } from "react-router-dom";
import { auth } from "./firebase";

function Login() {
  const history = useHistory();
  const [email, setEmail] = useState("");
  // console.log(email);
  const [password, setPassword] = useState("");
  const signIn = (e) => {
    e.preventDefault(); //help not to refresh
    auth
      .signInWithEmailAndPassword(email, password)
      .then((auth) => {
        history.push("/");
      })

      .catch((error) => alert(error.message));
  };

  const register = (e) => {
    e.preventDefault();
    auth
      .createUserWithEmailAndPassword(email, password)
      .then((auth) => {
        console.log(auth);
        if (auth) {
          history.push("/");
        }
      })
      .catch((error) => alert(error.message));
  };

  return (
    <div className="login">
      <Link to="/">
        <img
          className="login_logo"
          src="https://upload.wikimedia.org/wikipedia/commons/0/0f/Logo_Netflix.png"
        />
      </Link>
      <div className="login_container">
        <h1>Sign-in</h1>
        <form>
          <h5>Email-id</h5>
          <input
            type="text"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
          <h5>Password</h5>
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
          <button className="login_signInButton" type="submit" onClick={signIn}>
            Sign In
          </button>
        </form>
        <p>
          These "Conditions of Use" constitute an electronic record within the
          meaning of the applicable law. This electronic record is generated by
          a computer system and does not require any physical or digital
          signatures.
        </p>
        <button className="login_RegisterInButton" onClick={register}>
          Create an Netflix Account
        </button>
      </div>
    </div>
  );
}

export default Login;

//THIS IS MY CODE

// import React, { useState } from "react";
// import { Link } from "react-router-dom";
// import "./Login.css";

// function Login() {
//   const [email, setEmail] = useState("");
//   const [password, setPassword] = useState("");
//   return (
//     <div>
//       <div className="Login">
//         <Link to="/">
//           <img
//             src="https://upload.wikimedia.org/wikipedia/commons/0/0f/Logo_Netflix.png"
//             className="Login_logo"
//           />
//         </Link>
//         <div className="login_container">
//           <h className="login_signIn"> Sign In</h>
//           <form>
//             <h5>Email-Id</h5>
//             <input type="text" />
//             <h5>Password</h5>
//             <input type="password" />
//           </form>
//           <Link to="/">
//             <button className="login_signInButton">
//               Sign-In to make account
//             </button>
//           </Link>
//           <p className="p">
//             By clicking submit you agree to the Terms and Conditions. By
//             clicking submit you are agreeing to the Terms and Conditions.
//           </p>
//           <Link to="/">
//             <button className="login_createButton">
//               Create an Netflix Account
//             </button>
//           </Link>
//         </div>
//       </div>
//     </div>
//   );
// }

// export default Login;
